"""
Data Schemas & Type Definitions
===============================

This module serves as the central registry for data structures, type hints,
and validation schemas used throughout the project. It acts as the "contract"
layer that enforces consistency between the Python logic, the LLM interfaces,
and the Prompt templates.

Module Overview
---------------
- **typings.py**: Defines common Python type aliases (e.g., `Paths`, `Domain`,
  `BatchInputs`) to facilitate static type checking and maintain code clarity.

- **prompt_args.py**: Pydantic models that define the inputs required by
  prompt templates. The fields in these classes must map 1:1 to the
  placeholders (e.g., `{instructions}`) in the raw text templates.

- **llm_task_outputs.py**: Pydantic models used to parse, validate, and structure
  the raw JSON responses generated by LLMs. They enforce strict schema compliance
  and typically include reasoning fields to encourage Chain-of-Thought generation.
"""
