"""
LLM Task Output Schemas
=======================

This module defines the Pydantic models used to validate and structure the
JSON outputs generated by the LLM.

Design Philosophy:
    Most models include a "reasoning" field. This is intentional to induce
    Chain-of-Thought (CoT) reasoning within the LLM before it commits to a
    structured result (like a PDDL string or a boolean flag), thereby
    improving the robustness of the final output.
"""

from typing import List, Optional, Tuple

from pydantic import BaseModel, Field


class LLMTaskOutputs(BaseModel):
    """Base class for all LLM structured outputs."""
    pass


# ==========================================
# Atomic Domain Generation
# ==========================================

class InitialDomainOutputs(LLMTaskOutputs):
    """Output schema for the VLM-based initial domain generation step."""
    action_description: str
    precondition_reasoning: str
    effect_reasoning: str
    invented_predicates: List[Tuple[str, str]] = Field(default_factory=list)
    PDDL_action_name: str
    PDDL_action: str


class HolisticReviseDomainOutputs(LLMTaskOutputs):
    """Output schema for the holistic revision of the PDDL domain."""
    reasoning: str
    revised_domain: str


class RefineFromSolvabilityCheckOutputs(LLMTaskOutputs):
    """Output schema for refining the domain based on planner failures."""
    reasoning: str
    refined_domain: str


class RefineFromSolutionVerificationOutputs(LLMTaskOutputs):
    """Output schema for refining the domain based on semantic verification failures."""
    reasoning: str
    refined_domain: str


class GenerateTestProblemsOutputs(LLMTaskOutputs):
    """Output schema for generating PDDL test problems."""
    reasoning: str
    problems: List[str]


class VerifySolutionOutputs(LLMTaskOutputs):
    """Output schema for the semantic verification of a plan."""
    reasoning: str
    task_success: bool


# ==========================================
# Domain Fusion
# ==========================================

class CheckMergePredicatesOutputs(LLMTaskOutputs):
    """Output schema for checking if two predicates are semantically equivalent."""
    reasoning: str
    merge_flag: bool
    new_predicate: Optional[List[str]] = None


class UpdateActionStringOutputs(LLMTaskOutputs):
    """Output schema for updating an action string after predicate merging."""
    reasoning: str
    updated_action: str


class CheckMergeActionsOutputs(LLMTaskOutputs):
    """Output schema for checking if two actions are semantically equivalent."""
    reasoning: str
    merge_flag: bool
    new_operator_name: Optional[str] = None
    new_operator: Optional[str] = None


# ==========================================
# Task Planner
# ==========================================

class GenerateProblemOutputs(LLMTaskOutputs):
    """Output schema for grounding a visual task into a PDDL problem."""
    reasoning: str
    objects: List[str]
    init: List[str]
    goal: str


# ==========================================
# Baselines (Comparison Methods)
# ==========================================

class VLMCoTOutputs(LLMTaskOutputs):
    reasoning: str
    plan_sequence: List[str]


class VLMCoTPDDLOutputs(LLMTaskOutputs):
    reasoning: str
    domain: str
    problem: str


# IVML Baselines
class IVMLBoNOutputs(LLMTaskOutputs):
    reasoning: str
    domain_index: str


class IVMLInitializationOutputs(LLMTaskOutputs):
    reasoning: str
    domain: str


class IVMLOptOutputs(LLMTaskOutputs):
    reasoning: str
    feedback: str


class IVMLProblemOutputs(LLMTaskOutputs):
    reasoning: str
    problem: str


class IVMLUpdateOutputs(LLMTaskOutputs):
    reasoning: str
    thought: str
    domain: str


# Code as Policies
class CaPGenerateCodeOutputs(LLMTaskOutputs):
    reasoning: str
    code: str


class CaPFixBugsOutputs(LLMTaskOutputs):
    reasoning: str
    fixed_code: str
