"""
Solution Verification & Refinement Step
=======================================

This module implements the final validation stage of the atomic domain generation pipeline.
Even if a domain is syntactically correct and solvable by a planner, the generated plan
might be semantically nonsensical (e.g., teleporting objects). This module uses the LLM
to verify the semantic validity of the planner's solution and refines the domain if necessary.

Architecture Position:
    [Functional Steps / Middle Level] -> Called by atomic_domain.pipeline
    Uses LLM for semantic verification.
"""

import textwrap
from typing import Tuple

from unidomain.atomic_domain.post_process import save_and_post_process
from unidomain.configs.constants import File
from unidomain.configs.settings import config
from unidomain.schemas.llm_task_outputs import RefineFromSolutionVerificationOutputs, VerifySolutionOutputs
from unidomain.schemas.prompt_args import RefineFromSolutionVerificationPromptArgs, VerifySolutionPromptArgs
from unidomain.schemas.typings import Paths
from unidomain.services.llm_agent import LLMAgent, execute_llm_task
from unidomain.utils.runtime import setup_path

__all__ = ["run_verification_step", "run_verification_refinement_step"]

def _verify_solution(
    llm_agent: LLMAgent,
    prompt_args: VerifySolutionPromptArgs
) -> Tuple[bool, str]:
    """Call the LLM to verify the semantic correctness of the planner's solution.
    
    Args:
        llm_agent (LLMAgent): The LLM agent service.
        prompt_args (VerifySolutionPromptArgs): Arguments for LLM prompt.

    Returns:
        Tuple[bool, str]:
            - bool: True if the solution is semantically valid, False otherwise.
            - str: The LLM's reasoning or justification for the verdict.
    """

    # Call LLM and parse JSON into specified format
    outputs: VerifySolutionOutputs = execute_llm_task(
        llm_agent=llm_agent,
        prompt_template_path=config.prompt_path.verify_solution,
        prompt_args=prompt_args,
        validator=VerifySolutionOutputs,
    )

    # Return necessary information
    task_success = outputs.task_success
    reasoning = outputs.reasoning
    return task_success, reasoning


def run_verification_step(
    llm_agent: LLMAgent,
    domain_content: str,
    problem_content: str,
    action_sequence: str,
    output_dir: Paths
) -> Tuple[bool, str]:
    """Execute the solution verification step and log the reasoning.

    Args:
        llm_agent (LLMAgent): The LLM agent service.
        domain_content (str): The PDDL domain content.
        problem_content (str): The PDDL problem content used for verification.
        action_sequence (str): The plan (sequence of actions) generated by the planner.
        output_dir (Paths): Directory to save the verification logs.

    Returns:
        Tuple[bool, str]: (Is valid, Reasoning text).
    """

    output_dir = setup_path(output_dir)
    
    # Call LLM to verify solution
    prompt_args = VerifySolutionPromptArgs(
        domain=domain_content, problem=problem_content, action_sequence=action_sequence
    )
    is_valid, reasoning = _verify_solution(llm_agent, prompt_args)

    # Save reasoning log
    info_path = output_dir / File.REASONING
    info = textwrap.fill(reasoning, width=80, initial_indent='    ', subsequent_indent='    ')
    info_message = "Success!" if is_valid else "Failure!"
    info_message = info_message + f"\nReasoning: \n{info}"
    info_path.write_text(info_message, encoding="utf-8")

    return is_valid, reasoning


def _refine_from_solution_verification(
    llm_agent: LLMAgent,
    prompt_args: RefineFromSolutionVerificationPromptArgs
) -> str:
    """Call LLM to refine the atomic domain based on semantic verification errors..
    
    Args:
        llm_agent (LLMAgent): The LLM agent service.
        prompt_args (RefineFromSolutionVerificationPromptArgs): Arguments for LLM prompt.

    Returns:
        str: The refined domain string in PDDL format.
    """

    # Call LLM and parse JSON into specified format
    outputs: RefineFromSolutionVerificationOutputs = execute_llm_task(
        llm_agent=llm_agent,
        prompt_template_path=config.prompt_path.refine_from_solution_verification,
        prompt_args=prompt_args,
        validator=RefineFromSolutionVerificationOutputs,
    )

    # Return necessary information
    refined_domain = outputs.refined_domain
    return refined_domain


def run_verification_refinement_step(
    llm_agent: LLMAgent,
    domain_content: str,
    reasoning: str,
    instructions: str,
    output_dir: Paths
) -> None:
    """Execute the refinement step when solution verification fails.

    Args:
        llm_agent (LLMAgent): The LLM agent service.
        domain_content (str): The current domain content.
        reasoning (str): The failure reasoning provided by the verification step.
        instructions (str): The original task instructions.
        output_dir (Paths): Directory to save the refined result.

    Returns:
        None
    """
    output_dir = setup_path(output_dir)
    
    # Call LLM for refinement
    prompt_args = RefineFromSolutionVerificationPromptArgs(
        domain=domain_content,
        reasoning=reasoning,
        instructions=instructions
    )
    refined_str = _refine_from_solution_verification(llm_agent, prompt_args)

    save_and_post_process(refined_str, output_dir, stem=File.REFINED_DOMAIN_STEM)
